repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, development, --branch, main, --branch, release]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
        args: ['--float-to-top']
ci:
  autofix_commit_msg: 'ci(pre-commit.ci) auto fixes from pre-commit hooks \n\nfor more information, see https://pre-commit.ci '
  autoupdate_commit_msg: 'ci(pre-commit.ci): pre-commit autoupdate'
