version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-capivara-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-capivara-dev}
      POSTGRES_DB: ${POSTGRES_DB:-capivara-db}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - capivara.dev_data:/var/lib/postgresql/data

  capivara.dev:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: tail -f /dev/null
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-capivara-dev}:${POSTGRES_PASSWORD:-capivara-dev}@db:5432/${POSTGRES_DB:-capivara-db}
    ports:
      - 8888:8888
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  capivara.dev_data:
