[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "$version"

[tool.isort]
profile = "black"

[tool.black]
exclude = '''
^(
    \.git
  | data
  | docs
)$|\.tmp$
  |\.md$
'''
